#!/bin/bash

echo -e "\e[1;31m This is red text \e[0m"

echo -e "\e[1;33m This is yello text \e[0m"

echo -e "\e[1;32m This is yello text \e[0m"

echo -e "\e[1;34m This is blue text \e[0m"

echo -e "\e[1;35m This is magenta text \e[0m"
